includes:
  - /home/claireh/ebpf/configs/scalability/scalability_base.yml

benchmarks:
  dacapo-6e411f33:
    - luindex
    - zxing

configs:
  - "mmtk|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes|gc_threads-1|trace|no_add_rand|stress-16777216|large_heap"
  - "mmtk|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes|gc_threads-2|trace|no_add_rand|stress-16777216|large_heap"
  - "mmtk|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes|gc_threads-4|trace|no_add_rand|stress-16777216|large_heap"
  - "mmtk|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes|gc_threads-8|trace|no_add_rand|stress-16777216|large_heap"
  - "mmtk|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes|gc_threads-16|trace|no_add_rand|stress-16777216|large_heap"