# running runbms /home/claireh/ebpf/do_work_with_stat-tracing /home/claireh/ebpf/do_work_with_stat-tracing/worker_configs_id.yml -p "new_bpf_worker_id_20inv" -s 2
includes:
   - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

benchmarks:
  dacapochopin-f480064:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    # - jme
    - jython
    - luindex
    - lusearch
    # - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing

overrides:
  "suites.dacapochopin-f480064.timing_iteration": 5
  invocations: 20
  "suites.dacapochopin-f480064.callback": "probe.DacapoChopinCallback"
  "suites.dacapochopin-f480064.minheap": GenImmix
  "suites.dacapochopin-f480064.timeout": 1200
  "suites.dacapochopin-f480064.minheap_values.GenImmix": 
    avrora: 8
    batik: 407
    biojava: 196
    cassandra: 120
    eclipse: 722
    fop: 21 #manual
    graphchi: 256 #artificial
    h2: 1242
    h2o: 99
    jme: 236
    jython: 90 #manual
    luindex: 28 #manual
    lusearch: 28
    #pmd: .inf
    sunflow: 29
    tomcat: 51
    xalan: 22
    zxing: 432

runtimes:
  worker_tracing:
    type: OpenJDK
    release: 11
    home: "/home/claireh/openjdk/build/id/jdk"

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/claireh/probes /home/claireh/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/claireh/probes -Dprobes=RustMMTk"
  gc_threads:
    type: EnvVar
    var: MMTK_THREADS
    val: '{0}'
  bpftrace:
    type: Companion
    val: "sudo /opt/bpftrace/bpftrace-0.16.0-llvm-14 '/home/claireh/ebpf/do_work_with_stat-tracing/worker_id.bt'"
  no_add_rand:
    type: Wrapper
    val: "setarch x86_64 -R"

configs:
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-1|bpftrace|no_add_rand"
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-2|bpftrace|no_add_rand"
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-4|bpftrace|no_add_rand"
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-8|bpftrace|no_add_rand"
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-16|bpftrace|no_add_rand"
  - "worker_tracing|ms|s|c2|mmtk_gc-GenImmix|tph|probes_cp|probes|gc_threads-32|bpftrace|no_add_rand"
  