includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

suites:
  dacapo-0d047f55:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-0d047f55.jar
    timing_iteration: 5
    timeout: 1200
    callback: "probe.DacapoChopinCallback"
    invocations: 10

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/claireh/probes/out /home/claireh/probes/out/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/claireh/probes/out -Dprobes=RustMMTk"
  gc_threads:
    type: EnvVar
    var: MMTK_THREADS
    val: '{0}'
  no_add_rand:
    type: Wrapper
    val: "setarch x86_64 -R"
  # set stress interval (bytes)
  stress:
    type: EnvVar
    var: MMTK_STRESS_FACTOR
    val: "{0}"
  # sufficiently large heap so that GC is never triggered by a full heap
  large_heap:
    type: JVMArg
    val: "-Xms10G -Xmx10G"